# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grabotp < Formula
  desc "A simple tool to fetch recent OTPs from your Gmail account."
  homepage "https://github.com/pranavmangal/grabotp"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pranavmangal/grabotp/releases/download/0.2.0/grabotp_0.2.0_darwin_x86_64.tar.gz"
      sha256 "8a08a654272b89a7677d503e029b45818c342c372b1a1246420f3e9faef7a191"

      def install
        bin.install "grabotp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pranavmangal/grabotp/releases/download/0.2.0/grabotp_0.2.0_darwin_arm64.tar.gz"
      sha256 "dcd7169950788c270a742f8dd4cbf7ab260462514823a561e64bfa41725c9ddd"

      def install
        bin.install "grabotp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pranavmangal/grabotp/releases/download/0.2.0/grabotp_0.2.0_linux_x86_64.tar.gz"
      sha256 "8248748d4f24fd4a1b79147f1139e29e887ca419a603c0c4430362f7bb08858a"
      def install
        bin.install "grabotp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pranavmangal/grabotp/releases/download/0.2.0/grabotp_0.2.0_linux_arm64.tar.gz"
      sha256 "af91ae85d93d32e3379fe8205d09c1e162dd953586a23f02b009a3f9b6759e82"
      def install
        bin.install "grabotp"
      end
    end
  end
end
