# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grabotp < Formula
  desc "A simple tool to fetch recent OTPs from your Gmail account."
  homepage "https://github.com/pranavmangal/grabotp"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pranavmangal/grabotp/releases/download/0.1.0/grabotp_Darwin_x86_64.tar.gz"
      sha256 "009d878dc7dd0fee96adf5ddd7efdb6f9c577160f99e173aab6468d97c2b4c1b"

      def install
        bin.install "grabotp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pranavmangal/grabotp/releases/download/0.1.0/grabotp_Darwin_arm64.tar.gz"
      sha256 "eaa74c2660c103314466a5e93f7962833c3609ca1b882b4495fddc22fcb49d2c"

      def install
        bin.install "grabotp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/pranavmangal/grabotp/releases/download/0.1.0/grabotp_Linux_x86_64.tar.gz"
      sha256 "920657bbd99e61e9e54df3aabe18bc5456054cd81e9b55f2d6dbd32a6749b1a9"
      def install
        bin.install "grabotp"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/pranavmangal/grabotp/releases/download/0.1.0/grabotp_Linux_arm64.tar.gz"
      sha256 "36a118f1f5a4591ec15b35fa4753f1273047d72ca82c6c578fd9ab83835efc14"
      def install
        bin.install "grabotp"
      end
    end
  end
end
