# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Termq < Formula
  desc "A simple tool to query LLMs from the terminal."
  homepage "https://github.com/pranavmangal/termq"
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/pranavmangal/termq/releases/download/0.2.0/termq_Darwin_x86_64.tar.gz"
      sha256 "4e382ff70b9b51b0cdeb1e774a533d4d18f1874d3c74a3ed30dda0f4c879ee2f"

      def install
        bin.install "tq"
      end
    end
    on_arm do
      url "https://github.com/pranavmangal/termq/releases/download/0.2.0/termq_Darwin_arm64.tar.gz"
      sha256 "39e1ab24a04123b5670f814736d6b9894c609f108c8120b94f324a91426239ab"

      def install
        bin.install "tq"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pranavmangal/termq/releases/download/0.2.0/termq_Linux_x86_64.tar.gz"
        sha256 "69d293b36a39cf6a36e06f5e800f1076108fe52fd9839d381d04a21345449756"

        def install
          bin.install "tq"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pranavmangal/termq/releases/download/0.2.0/termq_Linux_arm64.tar.gz"
        sha256 "cc812d86ef08b7296d4a1aade3e46d388d78314c5575e117bc56c54af0f7769e"

        def install
          bin.install "tq"
        end
      end
    end
  end
end
