# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Termq < Formula
  desc "A simple tool to query LLMs from the terminal."
  homepage "https://github.com/pranavmangal/termq"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pranavmangal/termq/releases/download/0.2.2/termq_Darwin_x86_64.tar.gz"
      sha256 "7ad3b101067d979bfc02a12c2653a283ba45e84cb9956748c358c8ce2892308a"

      def install
        bin.install "tq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pranavmangal/termq/releases/download/0.2.2/termq_Darwin_arm64.tar.gz"
      sha256 "074a6beff9eb04ea8ad7ead79eddb6c7223547b1fa89803484b410ae6411d35d"

      def install
        bin.install "tq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pranavmangal/termq/releases/download/0.2.2/termq_Linux_x86_64.tar.gz"
        sha256 "73f785c54cf488955844d2137a2137617487cdd9936ee18aeca528544743a4af"

        def install
          bin.install "tq"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pranavmangal/termq/releases/download/0.2.2/termq_Linux_arm64.tar.gz"
        sha256 "b192619c5b7f7f36aa7e612b117f971c4d2fee32c7ae152de609f64684cbe051"

        def install
          bin.install "tq"
        end
      end
    end
  end
end
